[opener]
epub = [
  { run = "ebook-viewer %s", orphan = true, desc = "Calibre Ebook Viewer", for = "unix" },
]

[open]
rules = [
  # Force epub to open, not extract
  { url = "*.epub", use = "epub" },
]
