#Themes
scrollback_lines 1000000

include $HOME/.cache/wal/colors-kitty.conf

include current-theme.conf

# foreground #CDD6F4
# background #1E1E2E
# selection_foreground #1E1E2E
# selection_background #CDD6F4

shell zsh
allow_closing_with_processes yes
font_family      Hack Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
